title: Git
email: info@git-compendium.info
description: >- # this means to ignore newlines until "baseurl:"
  Project Management for Developers and DevOps Teams
github_username:  git-compendium

theme: jekyll-theme-hacker
plugins:
  - jekyll-feed
